### ISSUE TITLE
Moving Average Calculation

### ISSUE THREAD

**Issue by Brunez3BD** [keyro90/AFArray#4]
I'm having trouble with this code. I want to calculate the moving average of a series of M values.
I first inizialize an empty array, then i read the value from an ultrasonic sensor, do some calculation and then I "delete" the first element of the array with slice() (row 50) and then add the new value to the end of the array (row 52). In this way I have an array with the lasts M value of the sensors.
The sketch works for a few times then it freeze completely, I assume is a memory issue and I don't know how to solve this
[MovingAverageFilter.zip](https://github.com/keyro90/AFArray/files/1424287/MovingAverageFilter.zip)

**Comment by keyro90** [comment]
Hi @Brunez3BD ,
today 0.3b version has been released and probably this bug has resolved.
Try with it and let me know.
Thank you.
